# Generated by Django 5.2.9 on 2026-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="monthly_budget",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
