# Generated by Django 5.2.10 on 2026-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="familymember",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="familymember",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MEMBER", "Member"),
                    ("Visitor", "Visitor"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="familymember",
            name="family_head",
        ),
    ]
