# Generated by Django 5.2.10 on 2026-01-12 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
