# Generated by Django 5.2.9 on 2026-01-14 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_remove_expense_timestamp_expense_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-date"], "verbose_name_plural": "Expenses"},
        ),
        migrations.AddField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("RELIGION ABAYA", "Religion Abaya"),
                    ("GROCERIES", "Groceries"),
                    ("UTILITIES", "Utilities"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("TRANSPORT", "Transport"),
                    ("HEALTH", "Health"),
                    ("EDUCATION", "Education"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
