# Generated by Django 5.2.10 on 2026-03-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_familymember_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="income_source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
