# Generated by Django 5.2.10 on 2026-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_familymember_income_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymember",
            name="income_source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
