# Generated by Django 5.2.10 on 2026-03-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_budget_monthly_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MemberCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="familymember",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="familymember",
            name="father_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="familymember",
            name="mother_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="familymember",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="familymember",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("CLOTHS", "cloths"),
                    ("FOODS", "foods"),
                    ("GROCERIES", "Groceries"),
                    ("UTILITIES", "Utilities"),
                    ("ENTERTAINMENT", "Entertainment"),
                    ("TRANSPORT", "Transport"),
                    ("HEALTH", "Health"),
                    ("EDUCATION", "Education"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="familymember",
            name="income_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="expenses.incomesource",
            ),
        ),
        migrations.CreateModel(
            name="Expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenditures",
                        to="expenses.familymember",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenditures",
                        to="expenses.membercategory",
                    ),
                ),
            ],
        ),
    ]
