# Generated by Django 5.2.10 on 2026-03-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_incomesource_membercategory_familymember_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
